# Generated by Django 5.0.6 on 2024-05-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amenity",
            old_name="uploadted_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="uploadted_at",
            new_name="updated_at",
        ),
    ]
