# Generated by Django 5.0.6 on 2024-05-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_experience_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="uploadted_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="perk",
            old_name="uploadted_at",
            new_name="updated_at",
        ),
    ]
