# Generated by Django 5.0.6 on 2024-05-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="uploadted_at",
            new_name="updated_at",
        ),
    ]
